## Think connectors deployment with multiple replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: headless
          args:
            - --server
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
## HEADLESS Service
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
